development: &default
  # haml @globals (default)
  globals:
    robots:   'index,follow,noodp,noydir'
    title:    'ewg-theme-simple'
    language: 'de'
    description: 'ewg-theme-simple'
    keywords: 'easy-website-generator'

  # browser-sync
  server:
    port: 9294
    open: "external"
    notify: true
    startPath: 'index.html'
    server:
      baseDir: './dist'
    ui:
      port: 8080
      weinre:
        port: 9090
    ghostMode:
      clicks: true
      forms: true
      scroll: true

  # do not change unless you know why ;)
  generators:
    folder: './ewg'

  paths:
    src:
      base:       './src'
      images:     'assets/images'
      scripts:    'assets/scripts'
      styles:     'assets/styles'
      public:     'assets/public'
      views:      'views'
    dist:
      base:       './dist'
      images:     'images'
      scripts:    'scripts'
      styles:     'styles'
      public:     ''
      views:      ''

  template:
    run_after_copy:
      # read the README.md for the moment you have to doit manually
      - 'npm install'

test:
  <<: *default

production:
  <<: *default
